# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  # Trigger the workflow on push or pull request,
  push:
    branches: [main, stable]
  pull_request:
    # These types of PRs
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install # will run `yarn install` command
      #- uses: borales/actions-yarn@v3.0.0
      #  with:
      #    cmd: test # will run `yarn test` command
      #- uses: borales/actions-yarn@v3.0.0
      #  with:
      #    cmd: type-check # will run `yarn type-check` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint # will run `yarn lint` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: build # will run `yarn start` command
